### ISSUE TITLE
Getting a very long image in windows

### ISSUE THREAD

**Issue by yuyudhan** [openpaperwork/pyinsane#36]
While in linux system it the scan_adf.py and scan.py are working fine, but in windows systems the scripts are generating very long images. Please see attachment.
Height of scanned image is 9000 px.

![1](https://user-images.githubusercontent.com/3090231/33996205-5644e3ea-e095-11e7-9a04-36270ec0579f.jpg)

Is there a setting which can be set to correct this issue?

**Comment by jflesch** [comment]
Can you paste the output of [list_all.py](https://github.com/openpaperwork/pyinsane/blob/master/examples/list_all.py) in a [pastebin](https://gist.github.com/) and post the link here please ?

**Comment by yuyudhan** [comment]
Here: @jflesch 

https://pastebin.com/0LSf5NET

**Comment by jflesch** [comment]
```
  Option: yextent
    Title:
    Desc:
    Type: None
    Unit: None
    Size: 4
    Capabilities: Access: rw                                                                                                Constraint type: None
    Constraint: (32, 36600)
    Value: 36600
```

Hm, 36600 is far too much. I think your driver is returning a crappy maximum size ...

As a workaround, just before you scan, you can try to add something like:
```
pyinsane2.set_scanner_opt(device, 'yextent', [2550 * 2])  # 2 times the max xextend
```

If it does work, I guess I will have to add yet-another-workaround in `pyinsane2.maximize_scan_area`.
